name: .NET Build/Test + Copilot Agent Remediation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      id: test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" || echo "test_failed=true" >> $GITHUB_OUTPUT
      
    - name: Upload test results
      if: steps.test.outputs.test_failed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/*.trx
          **/logs/**
          
    - name: Run Copilot Agent Remediation
      if: steps.test.outputs.test_failed == 'true'
      uses: github/copilot-actionbot-agent@main
      with:
        test_results_path: '**/*.trx'
        remediation_mode: 'issue'
        github_token: ${{ secrets.GITHUB_TOKEN }}